# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:32:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AdminUser(BaseModel):
    familyName: Optional[str] = Field(
        None, description='Optional. Last/family name of the first admin user.'
    )
    givenName: Optional[str] = Field(
        None, description='Optional. First/given name of the first admin user.'
    )


class CancelOperationRequest(BaseModel):
    pass


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    STATE_DEPLOYING = 'STATE_DEPLOYING'
    STATE_DEPLOYED = 'STATE_DEPLOYED'
    STATE_TERMINATING = 'STATE_TERMINATING'
    STATE_FAILED = 'STATE_FAILED'
    STATE_TERMINATING_FAILED = 'STATE_TERMINATING_FAILED'
    STATE_TERMINATED = 'STATE_TERMINATED'


class ContactCenterQuota(BaseModel):
    contactCenterCountLimit: Optional[int] = Field(
        None,
        description='Reflects the count limit of contact centers on a billing account.',
    )
    contactCenterCountSum: Optional[int] = Field(
        None,
        description='Reflects the count sum of contact centers on a billing account.',
    )


class Empty(BaseModel):
    pass


class InstanceSize(Enum):
    INSTANCE_SIZE_UNSPECIFIED = 'INSTANCE_SIZE_UNSPECIFIED'
    STANDARD_SMALL = 'STANDARD_SMALL'
    STANDARD_MEDIUM = 'STANDARD_MEDIUM'
    STANDARD_LARGE = 'STANDARD_LARGE'
    STANDARD_XLARGE = 'STANDARD_XLARGE'
    STANDARD_2XLARGE = 'STANDARD_2XLARGE'
    STANDARD_3XLARGE = 'STANDARD_3XLARGE'


class InstanceConfig(BaseModel):
    instanceSize: Optional[InstanceSize] = Field(
        None, description='The instance size of this the instance configuration.'
    )


class Location(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The friendly name for this location, typically a nearby city name. For example, "Tokyo".',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"}',
    )
    locationId: Optional[str] = Field(
        None,
        description='The canonical id for this location. For example: `"us-east1"`.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata. For example the available capacity at the given location.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for the location, which may vary between implementations. For example: `"projects/example-project/locations/us-east1"`',
    )


class SAMLParams(BaseModel):
    certificate: Optional[str] = Field(None, description='SAML certificate')
    entityId: Optional[str] = Field(None, description='Entity id URL')
    ssoUri: Optional[str] = Field(None, description='Single sign-on URL')
    userEmail: Optional[str] = Field(
        None, description='Email address of the first admin users.'
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class URIs(BaseModel):
    chatBotUri: Optional[str] = Field(
        None, description='Chat Bot Uri of the ContactCenter'
    )
    mediaUri: Optional[str] = Field(None, description='Media Uri of the ContactCenter.')
    rootUri: Optional[str] = Field(None, description='Root Uri of the ContactCenter.')
    virtualAgentStreamingServiceUri: Optional[str] = Field(
        None, description='Virtual Agent Streaming Service Uri of the ContactCenter.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class ContactCenter(BaseModel):
    adminUser: Optional[AdminUser] = Field(
        None,
        description='Optional. Info about the first admin user, such as given name and family name.',
    )
    ccaipManagedUsers: Optional[bool] = Field(
        None,
        description='Optional. Whether to enable users to be created in the CCAIP-instance concurrently to having users in Cloud identity',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. [Output only] Create time stamp'
    )
    customerDomainPrefix: Optional[str] = Field(
        None,
        description='Required. Immutable. At least 2 and max 16 char long, must conform to [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt).',
    )
    displayName: Optional[str] = Field(
        None, description='Required. A user friendly name for the ContactCenter.'
    )
    instanceConfig: Optional[InstanceConfig] = Field(
        None,
        description='The configuration of this instance, it is currently immutable once created.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Labels as key value pairs'
    )
    name: Optional[str] = Field(None, description='name of resource')
    samlParams: Optional[SAMLParams] = Field(
        None, description='Optional. Params that sets up Google as IdP.'
    )
    state: Optional[State] = Field(
        None, description='Output only. The state of this contact center.'
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. [Output only] Update time stamp'
    )
    uris: Optional[URIs] = Field(
        None, description='Output only. URIs to access the deployed ContactCenters.'
    )
    userEmail: Optional[str] = Field(
        None, description='Optional. Email address of the first admin user.'
    )


class ListContactCentersResponse(BaseModel):
    contactCenters: Optional[List[ContactCenter]] = Field(
        None, description='The list of ContactCenter'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token identifying a page of results the server should return.',
    )
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class ListLocationsResponse(BaseModel):
    locations: Optional[List[Location]] = Field(
        None,
        description='A list of locations that matches the specified filter in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class OperationMetadata(BaseModel):
    apiVersion: Optional[str] = Field(
        None, description='Output only. API version used to start the operation.'
    )
    contactCenter: Optional[ContactCenter] = Field(
        None, description='Contact center information for this request'
    )
    createTime: Optional[str] = Field(
        None, description='Output only. The time the operation was created.'
    )
    endTime: Optional[str] = Field(
        None, description='Output only. The time the operation finished running.'
    )
    requestedCancellation: Optional[bool] = Field(
        None,
        description='Output only. Identifies whether the user has requested cancellation of the operation. Operations that have been cancelled successfully have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.',
    )
    statusMessage: Optional[str] = Field(
        None, description='Output only. Human-readable status of the operation, if any.'
    )
    target: Optional[str] = Field(
        None,
        description='Output only. Server-defined resource path for the target of the operation.',
    )
    verb: Optional[str] = Field(
        None, description='Output only. Name of the verb executed by the operation.'
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )
